# Generated by Django 4.1.4 on 2022-12-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='sdhf', upload_to='pics'),
            preserve_default=False,
        ),
    ]
